# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Invidious"
  org.opencontainers.image.description:
    "Invidious - Privacy-friendly YouTube frontend"
  org.opencontainers.image.source:
    "https://github.com/tserra30/Invidious-add-on-"
  org.opencontainers.image.licenses: "Apache 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
